# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'M18_RestAPI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for M18_RestAPI
pod 'SnapKit', '~> 5.0.0'
pod 'Alamofire'

end
