# Uncomment the next line to define a global platform for your project
# platform :ios, '15.2'

target 'M20_LocalSaveData' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for M20_LocalSaveData

end
pod 'SnapKit', '~> 5.0.0'
